/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fseoedndjvvjikwcryck"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZW9lZG5kanZ2amlrd2NyeWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1ODE1NzEsImV4cCI6MjA3NjE1NzU3MX0.rv-gk7070dXY-E3UP-VRALH_uHr3L-c4ltbvCBPznqo"